### ISSUE TITLE
Node.js 8.10 is EOL, please migrate your functions to a newer runtime version

### ISSUE THREAD

**Issue by veblock** [SumoLogic/sumologic-aws-lambda#103]
Any immediate plans to upgrade the runtime node version?

**Comment by scastria** [comment]
Agreed.  Can we get a status on migrating to nodejs10.x runtime?

**Comment by duchatran** [comment]
We'll start testing our functions early next quarter (beginning Nov 2019). According to AWS, only new functions won't be created after December and existing functions won't be updated after Feb 2020, so it's a couple of months out. Chances are all you need to do is just to change the existing engine to Node 10.

**Comment by himanshu219** [comment]
Nodejs migration is fixed in this [PR](https://github.com/SumoLogic/sumologic-aws-lambda/pull/104)

**Comment by shlomi-viz** [comment]
@duchatran any updates on when this should be released?

**Comment by 4ragumurthy** [comment]
Please refer this Sumo Logic Support [KB](https://support.sumologic.com/hc/en-us/articles/360038393133)
----------------------
Sumo Logic has validated that there are no compatibility issues with the running of existing functions under the Node.js 10.x runtime. 

Sumo Logic has already updated all SAM applications and existing CloudFormation templates with the Node.js 10 runtime and recommend re-deploying the new functions as they fix all deprecation warnings. 

We expect the “sumologic-process-logs” AWS Lambda blueprint, to be updated by  December 15, 2019, ahead of the deprecation date.

**Comment by 4ragumurthy** [comment]
The “sumologic-process-logs” AWS Lambda blueprint has been updated by AWS to use nodejs 12.x

**Comment by alex4108** [comment]
Hello,

The following three files still contain references to nodejs8.10 and nodejs8.10 is unavailable to create in Lambda as of yesterday. https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

Please advise if these can be ignored.

https://github.com/SumoLogic/sumologic-aws-lambda/blob/master/loggroup-lambda-connector/test/test_loggroup_lambda_connector.py
https://github.com/SumoLogic/sumologic-aws-lambda/blob/master/loggroup-lambda-connector/test/loggroup-lambda-cft.json
https://github.com/SumoLogic/sumologic-aws-lambda/blob/master/cloudwatchevents/guardduty/cloudwatchevents.json

**Comment by himanshu219** [comment]
Hi,

https://github.com/SumoLogic/sumologic-aws-lambda/blob/master/loggroup-lambda-connector/test/test_loggroup_lambda_connector.py

This can be ignored because we are creating a dummy function here for
testing. But we'll update it.


https://github.com/SumoLogic/sumologic-aws-lambda/blob/master/loggroup-lambda-connector/test/loggroup-lambda-cft.json
https://github.com/SumoLogic/sumologic-aws-lambda/blob/master/cloudwatchevents/guardduty/cloudwatchevents.json

For both these integrations we are using SAM application now and it's the
recommended way to go. But we'll fix just in case someone wants to use
these old templates.

Thanks

Himanshu Pal

Integration Engineer II, AppDev Team


<https://www.linkedin.com/in/himanshu-pal/>
<https://twitter.com/himanshu_pal_> [image: https://github.com/himanshu219/]
<https://github.com/himanshu219/>
<https://www.glassdoor.com/Overview/Working-at-Sumo-Logic-EI_IE621848.11,21.htm>
<https://www.sumologic.com/events/illuminate2018/>

**Comment by himanshu219** [comment]
https://github.com/SumoLogic/sumologic-aws-lambda/blob/master/loggroup-lambda-connector/test/test_loggroup_lambda_connector.py

This can be ignored because we are creating a dummy function here for testing. But we'll update it.


https://github.com/SumoLogic/sumologic-aws-lambda/blob/master/loggroup-lambda-connector/test/loggroup-lambda-cft.json
https://github.com/SumoLogic/sumologic-aws-lambda/blob/master/cloudwatchevents/guardduty/cloudwatchevents.json

For both these integrations we are using SAM application now and it's the recommended way to go. But we'll fix just in case someone wants to use these old templates.

**Comment by craigwatkinson** [comment]
The CloudFormation template referenced on the following page still uses Node.js 8.10: https://help.sumologic.com/03Send-Data/Collect-from-Other-Data-Sources/Auto-Subscribe_AWS_Log_Groups_to_a_Lambda_Function

**Comment by himanshu219** [comment]
@craigwatkinson I have updated the link. 
@alex4108 these are fixed in this [PR](https://github.com/SumoLogic/sumologic-aws-lambda/pull/111)
