### ISSUE TITLE
First event into new logGroup won't invoke the subscribing function.

### ISSUE THREAD

**Issue by amitbajaj45** [SumoLogic/sumologic-aws-lambda#112]
If new log group creation is binded with new event creation, for example, in case of first run of new lambda function. Only after creation of Log group, event rule will be invoked to attach it to target lambda function.
So first event will not be captured in target lambda function. Only subsequent events will be captured.

**Comment by himanshu219** [comment]
yes I think this is a con. Because unless the log group exists lambda connector function can't subscribe to it. Then only subsequent events will be captured by cloudwatch collector lambda function. One hacky way is to create the empty log group by manually running your new lambda though it would be tedious if there are in huge number.
